### ISSUE TITLE
Panics when launched in fargate backed container

### ISSUE THREAD

**Issue by boonew2** [Droplr/aws-env#15]
I switched some services in ECS to use Fargate instead of EC2 and it seems to cause aws-env to blow up.
```
2018/05/10 03:06:04 NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
panic: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
goroutine 1 [running]:
panic(0x6adf20, 0xc42000bfc0)
/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
log.Panic(0xc4200c5eb0, 0x1, 0x1)
/usr/local/Cellar/go/1.7.4/libexec/src/log/log.go:320 +0xc9
main.ExportVariables(0xc42001200d, 0x19, 0x0, 0x0)
/Users/aorfin/go/aws-env/aws-env.go:42 +0x254
main.main()
/Users/aorfin/go/aws-env/aws-env.go:19 +0x113
```

Binary is being pulled from latest [commit](https://github.com/Droplr/aws-env/raw/872ca7e45a8fdc519ff40745c56175ae81d3b66b/bin/aws-env-linux-amd64).

This looks like it could be a bug in the aws go sdk or something wonky in Fargate; I am pretty green to AWS and have zero go experience so I wasn't sure where to start on debugging this.

Any suggestions?

**Comment by orfin** [comment]
Hi! Unfortunately we haven't tested it on Fargate, however are you sure you have correctly configured IAM roles for your ECS tasks? IAMs should allow specific tasks to get & decrypt SSM parameters. 
It's described in this blog post: (under _Step 2: Create the IAM role and policies_)
https://aws.amazon.com/blogs/compute/managing-secrets-for-amazon-ecs-applications-using-parameter-store-and-iam-roles-for-tasks/

**Comment by boonew2** [comment]
I finally got back around to messing with this. The error was on my side.

I only had a `ExecutionRoleArn` in the task definition and was missing the `TaskRoleArn`. 

When run in EC2 the containers apparently picked up the InstanceProfile role that was attached to the LaunchConfiguration used for the auto scaling group and were able to access SSM through it, but in Fargate there wasn't any role applied that offered the needed aws creds auto-magically so it didn't do anything useful; I don't think there is anything to be fixed here at all!
