### ISSUE TITLE
Feature Request : Custom region

### ISSUE THREAD

**Issue by chris-verclytte** [Droplr/aws-env#17]
Hi,

What would you think about adding a customizable region that could be passed with a flag instead of using the `AWS_REGION` environment variable ? 

Here is my use case, I am currently using eu-west-3 (Paris) for most of my services. Unfortunately, SSM Parameter Store is not yet available in this region, thus I am currently putting my SSM Parameter Store data in eu-west-1 region.
But I don't want to put eu-west-1 as `AWS_REGION` env variable as it could cause some side effect with other services.

Instead, I would like to be able to define my image entrypoint with something like this : 
```sh
ENTRYPOINT ["/bin/bash", "-c", "eval $(aws-env --region eu-west-1)"]
``` 

What do you think about that ? Does it seem legit ?

**Comment by orfin** [comment]
Thanks for the idea! Im just wondering what do you think about invoking it like:

```
eval $(AWS_ENV_PATH=/prod/my-app/ AWS_REGION=eu-west-1 ./aws-env) && AWS_REGION=eu-west-3 node -e "console.log(process.env)"
```

I have not tested it but imho it should work as a workaround for now?

**Comment by chris-verclytte** [comment]
> The AWS_REGION env won't be propagated outside the eval statement, so subsequent commands won't have AWS_REGION modified.

I was missing that point. Thank you for the clarification !
