### ISSUE TITLE
Add license to repository

### ISSUE THREAD

**Issue by hallmark** [Droplr/aws-env#3]
Hi Droplr folks,

Thank you for publishing your project to the internet! I appreciate the functionality you've created here - I'd really like to use it in development of my project at work.  We're deploying our system to AWS and the injection of encrypted Parameters as env vars would be awesome for us.  One tiny bump is holding us back at the moment.

Would you be ok adding a license file to your repository?  GitHub has a [super easy set of license templates](https://help.github.com/articles/adding-a-license-to-a-repository/) to use.

I'd also kindly suggest/hope for Apache 2.0, MIT, or BSD.  Again, many thanks for the OSS contribution!

**Comment by orfin** [comment]
Hi @hallmark !
Thanks for your suggestion, we've just added missing MIT license to the project. Hope that will work for you!

Greetings, Antoni.

**Comment by orfin** [comment]
Hi @hallmark !
Thanks for your suggestion, we've just added missing MIT license to the project. Hope that will work for you!

Greetings, Antoni.
