### ISSUE TITLE
AWS-ENV in ECS doesn't read credentials from env vars

### ISSUE THREAD

**Issue by aolde** [Droplr/aws-env#9]
Hi,

We're using aws-env in ECS and therefore get our credentials through an `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI `environment variable that points to a relative URI where the credentials can be downloaded from. This doesn't seem to work with the current version of aws-env, as it's using the default config with anonymous credentials. However, if you supply the `defaults.Get().Config` ([defaults.go](https://github.com/aws/aws-sdk-go/blob/master/aws/defaults/defaults.go)) when creating new session the SDK will look at the above env-var among other things.

I have made the below change in a fork and it works well. Though, I wanted to check with you before submitting a PR if there are consequences to this that I'm not aware of.

**From**
```go
func CreateClient() *ssm.SSM {
	sess := session.Must(session.NewSession())
	return ssm.New(sess)
}
```

**To**
```go
func CreateClient() *ssm.SSM {
	cfg := defaults.Get().Config
	sess := session.Must(session.NewSession(cfg))
	return ssm.New(sess)
}
```

**Comment by otanner** [comment]
Hi,

Setting `AWS_SDK_LOAD_CONFIG=1` environment variable for the ECS Task enables the use of ECS Task IAM roles. This is something I've seen only needed with AWS SDK for Go. For local development it also enables the support for `AWS_PROFILE` (including assumed roles) and `AWS_DEFAULT_REGION`.

**Comment by orfin** [comment]
@aolde did @otanner's solution worked for you? Can we close this issue for now? :-)

**Comment by aolde** [comment]
It looks to be working while setting that env! I previously disregarded that variable as I didn't find any config stored on disk - didn't think that it also could change the way ECS behaves.
Thanks!
